### ISSUE TITLE
Add support for HDFS storage

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/hive-operator#263]
The hive-operator allows you to specify an S3 location but not a HDFS cluster. Add support to allow HDFS to be used as the storage target for hive tables.

Afterwards https://github.com/stackabletech/trino-operator/blob/bc442aa2f785208db5dd4ca98c2ba6d880370771/tests/templates/kuttl/smoke/check-s3.py#L91-L99 can be updated to the new mechanism.
It also servers as a perfect testcase

CRD proposal which matches the way we do in Trino: https://github.com/stackabletech/trino-operator/blob/bc442aa2f785208db5dd4ca98c2ba6d880370771/tests/templates/kuttl/smoke/10-install-trino.yaml.j2#L43-L57
```
spec:
  version: {{ test_scenario['values']['hive'] }}
  s3:
    reference: minio
  hdfs:
    configMap: hdfs
```

- [x] Implemented
- [x] Trino tests adopted (see comment above) and pass
- [x] Feature tracker updated
