### ISSUE TITLE
Standardize HDFS ConfigMap reference

### ISSUE THREAD

**Issue by adwk67** [stackabletech/hive-operator#404]
The Hive CRD currently has this:

```
        spec:
          clusterConfig:
            hdfs:
              configMap: hdfs
```

This should be brought inline with how this is done for HBase i.e.

```
      spec:
        clusterConfig:
          hdfsConfigMapName: hdfs
```
