### ISSUE TITLE
authentication between hive and its database based on secrets like airflow or superset

### ISSUE THREAD

**Issue by maxgruber19** [stackabletech/hive-operator#414]
Currently the connection between hive and its database is configured in the hivecluster itself. Because all the resources are likely to be stored in version control systems the credentials for the connection would be stored in plaintext.

I consider the following as insecure
```
clusterConfig:
    database:
      connString: jdbc:postgresql://postgresql:5432/hive
      user: hive
      password: hive
      dbType: postgres
```

I'd suggest something similar to airflow where a seperate secret is used to authenticate to its database 
```
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-airflow-credentials
type: Opaque
stringData:
  adminUser.username: airflow
  adminUser.firstname: Airflow
  adminUser.lastname: Admin
  adminUser.email: airflow@airflow.com
  adminUser.password: airflow
  connections.secretKey: thisISaSECRET_1234
  connections.sqlalchemyDatabaseUri: postgresql+psycopg2://airflow:airflow@airflow-postgresql.default.svc.cluster.local/airflow
  connections.celeryResultBackend: db+postgresql://airflow:airflow@airflow-postgresql.default.svc.cluster.local/airflow
  connections.celeryBrokerUrl: redis://:redis@airflow-redis-master:6379/0
```
