### ISSUE TITLE
Log files produced by Hive aren't processed by Vector

### ISSUE THREAD

**Issue by zaultooz** [stackabletech/hive-operator#479]
### Affected Stackable version

23.11.0

### Affected Apache Hive version

3.1.3

### Current and expected behavior

Currently none of the produced log statements in the **hive.log4j2.xml** is picked up by Vector and send to the aggregator, resulting in no logs from Hive appearing in our logging solution.

I would expect Vector would transform and propagate the logs similar to other Stackable components.

### Possible solution

Looking a bit into the matter, it seems the **files_log4j2** in vector.yaml cm doesn't take multi-line into account. The issue was resolved by changing the file entry in vector.yaml so it looks like this:
```
files_log4j2:
    type: file
    include:
        - /stackable/log/*/*.log4j2.xml
    line_delimiter: "\r\n"
    multiline:
        mode: halt_before
        start_pattern: ^<Event
        condition_pattern: ^<Event
        timeout_ms: 1000
```
    
I am unsure if there are other Stackable components using log4j2 currently so don't know if this is a suitable solution or it would be better to format everything from Hive one line.

### Environment

Client Version: v1.28.9
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.9

### Would you like to work on fixing this bug?

None
