### ISSUE TITLE
Ability to Override the Hive ConfigMap Configuration

### ISSUE THREAD

**Issue by CoderYellow** [stackabletech/hive-operator#528]
Currently, it appears that there is a controller monitoring and reconciling the ConfigMap for Hive. Any manual changes made to the ConfigMap are later overwritten by hardcoded configurations set by this controller. This behavior prevents any permanent custom configurations from being applied.

Could we look into modifying this behavior or providing a method to allow for persistent custom configurations?

**Comment by CoderYellow** [comment]
Is there currently a way to customize the log level for the metastore? Can this be configured within the HiveCluster CRD? Without this capability, troubleshooting becomes significantly more challenging.

**Comment by sbernauer** [comment]
Hi @CoderYellow,
we don't support configOverrides on all files, so the `metastore-log4j2.properties` is not supported.

However, what you probably want to do is use the logging mechanism we have added to the platform, which allow you fine-grained control, regardless of the actual different logging implementations in all the different tools.
You can find the documentation here: https://docs.stackable.tech/home/stable/concepts/logging, the specific one for Hive metastore here: https://docs.stackable.tech/home/stable/hive/usage-guide/logging

Without having tested it, your config could look something like
```yaml
spec:
  metastore:
    config:
      logging:
        containers:
          hive:
            console:
              level: DEBUG
            loggers:
              ROOT:
                level: DEBUG
```
